db:
  adapter: mysql
  host: 127.0.0.1
  port: 3306
  name: wtf
  user: root
  password: apple1234
#mongodb:
#  adapter: mongodb
#  host: 192.168.1.142
#  port: 27017
#  name: wyaoo
#  user: webwriter
#  password: webwriter